version: '3.1'

services:

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: online_shop
    ports:
      - "5433:5432"
    volumes:
    - ./init_db.sql:/docker-entrypoint-initdb.d/1_init_db.sql
